variables:
  BIN_PATH: .
#  GOVERSIONS: ['1.16']

before_script:
  - export GOPATH="$(pwd)/.gopath"
  - export GOPRIVATE="gitlab.com/ptxmac/*"
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "https://gitlab.com/"

build-test:
  stage: test
  parallel:
    matrix:
      - GOVERSION: ['1.16','1.17']
    
  image: golang:$GOVERSION
  script:
    - go build $BIN_PATH
    - go test ./... -v -coverprofile .testCoverage.txt
    - go tool cover -func=.testCoverage.txt
  artifacts:
    paths:
      - $CI_PROJECT_NAME
