name: Go
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    strategy:
        matrix:
            go: [ '1.17', '1.18', '1.19', '1.20', '1.21']
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Print go version
        run: go version

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v .

      - name: Cover
        run: |
          go test -race -coverprofile=cover.out -coverpkg=./... -v ./...
          go tool cover -html=cover.out -o cover.html

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v1
